# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.define "rails" do |rails|
    rails.vm.synced_folder "~/workspace/rails_demo/blog", "/home/vagrant/src"

    rails.vm.provision "ansible" do |ansible|
      ansible.playbook = "rails.yml"
      ansible.host_key_checking = false
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
      ansible.sudo = true
    end

#		rails.vm.provision "shell", inline: "cd ~/src/example && 
  end
end
